name: Build

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android build environment
        uses: android-actions/setup-android@v2
      - name: Create debug keystore for android
        run: |
          mkdir -p $HOME/.android
          keytool -genkey -v -keystore $HOME/.android/debug.keystore -storetype PKCS12 -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -noprompt -dname "CN=Tutorial, OU=TheInvader360, O=TheInvader360, L=Unknown, ST=Unknown, C=UK"
      - name: Build whole project with gradle
        run: ./gradlew build
